// Dummy users for authentication
export const dummyUsers = [
  {
    id: "u1",
    name: "Admin User",
    email: "shaibalsharif@gmail.com",
    password: "123456",
    role: "admin" as const,
    phone: "+8801712345678",
  },
  {
    id: "u2",
    name: "Finance Manager",
    email: "finance@example.com",
    password: "123456",
    role: "finance_manager" as const,
    phone: "+8801812345678",
  },
  {
    id: "u3",
    name: "Regular Member",
    email: "member@example.com",
    password: "123456",
    role: "member" as const,
    phone: "+8801912345678",
  },
]

// System settings
export const systemSettings = {
  monthlyDepositAmount: 2000, // Default monthly deposit amount
  depositDueDay: 10, // Day of month when deposit becomes late
  reminderDay: 7, // Day of month to send reminder
}

// Add fund accounts data
export const fundAccounts = {
  main: {
    name: "Main Bank Account",
    balance: 180000,
  },
  side: {
    name: "Side Account",
    balance: 65000,
  },
}

// Dummy deposit data
export const depositData = [
  {
    id: "d1",
    month: "May 2025",
    amount: 2000,
    transactionId: "TXN123456789",
    date: "05/01/2025",
    status: "verified",
    userId: "u3",
    userName: "Regular Member",
    isLate: false,
    isPartial: false,
    account: "main",
  },
  {
    id: "d2",
    month: "April 2025",
    amount: 2000,
    transactionId: "TXN987654321",
    date: "04/02/2025",
    status: "verified",
    userId: "u3",
    userName: "Regular Member",
    isLate: false,
    isPartial: false,
    account: "main",
  },
  {
    id: "d3",
    month: "May 2025",
    amount: 2000,
    transactionId: "TXN456789123",
    date: "05/05/2025",
    status: "pending",
    userId: "u2",
    userName: "Finance Manager",
    isLate: false,
    isPartial: false,
    account: "main",
  },
  {
    id: "d4",
    month: "March 2025",
    amount: 2000,
    transactionId: "TXN789123456",
    date: "03/01/2025",
    status: "verified",
    userId: "u3",
    userName: "Regular Member",
    isLate: false,
    isPartial: false,
    account: "side",
  },
  {
    id: "d5",
    month: "February 2025",
    amount: 2000,
    transactionId: "TXN321654987",
    date: "02/01/2025",
    status: "verified",
    userId: "u3",
    userName: "Regular Member",
    isLate: false,
    isPartial: false,
    account: "main",
  },
  {
    id: "d6",
    month: "May 2025",
    amount: 1000,
    transactionId: "TXN654987321",
    date: "05/12/2025",
    status: "verified",
    userId: "u2",
    userName: "Finance Manager",
    isLate: true,
    isPartial: true,
    account: "side",
  },
  {
    id: "d7",
    month: "May 2025",
    amount: 1000,
    transactionId: "TXN654987322",
    date: "05/15/2025",
    status: "verified",
    userId: "u2",
    userName: "Finance Manager",
    isLate: true,
    isPartial: true,
    account: "side",
  },
]

// Member deposit status - tracks which months each member has paid
export const memberDepositStatus = [
  {
    userId: "u1",
    userName: "Admin User",
    months: [
      { month: "January 2025", paid: true, isLate: false },
      { month: "February 2025", paid: true, isLate: false },
      { month: "March 2025", paid: true, isLate: false },
      { month: "April 2025", paid: true, isLate: false },
      { month: "May 2025", paid: true, isLate: false },
    ],
    totalPaid: 10000,
  },
  {
    userId: "u2",
    userName: "Finance Manager",
    months: [
      { month: "January 2025", paid: true, isLate: false },
      { month: "February 2025", paid: true, isLate: false },
      { month: "March 2025", paid: true, isLate: false },
      { month: "April 2025", paid: true, isLate: false },
      { month: "May 2025", paid: true, isLate: true },
    ],
    totalPaid: 10000,
  },
  {
    userId: "u3",
    userName: "Regular Member",
    months: [
      { month: "January 2025", paid: true, isLate: false },
      { month: "February 2025", paid: true, isLate: false },
      { month: "March 2025", paid: true, isLate: false },
      { month: "April 2025", paid: true, isLate: false },
      { month: "May 2025", paid: false, isLate: false },
    ],
    totalPaid: 8000,
  },
  {
    userId: "m1",
    userName: "Rahul Khan",
    months: [
      { month: "January 2025", paid: true, isLate: false },
      { month: "February 2025", paid: true, isLate: false },
      { month: "March 2025", paid: true, isLate: false },
      { month: "April 2025", paid: true, isLate: false },
      { month: "May 2025", paid: false, isLate: false },
    ],
    totalPaid: 8000,
  },
  {
    userId: "m2",
    userName: "Priya Sharma",
    months: [
      { month: "January 2025", paid: true, isLate: false },
      { month: "February 2025", paid: true, isLate: false },
      { month: "March 2025", paid: true, isLate: true },
      { month: "April 2025", paid: true, isLate: false },
      { month: "May 2025", paid: false, isLate: false },
    ],
    totalPaid: 8000,
  },
]

// Notifications
export const notificationData = [
  {
    id: "n1",
    userId: "u3",
    title: "Deposit Reminder",
    message: "Please deposit ৳2,000 for May 2025 before the 10th to avoid late fees.",
    date: "05/07/2025",
    read: false,
    type: "reminder",
  },
  {
    id: "n2",
    userId: "u3",
    title: "Deposit Due",
    message: "Your deposit for May 2025 is now overdue. Please make the payment as soon as possible.",
    date: "05/11/2025",
    read: false,
    type: "late",
  },
  {
    id: "n3",
    userId: "u2",
    title: "Deposit Verified",
    message: "Your deposit of ৳2,000 for April 2025 has been verified.",
    date: "04/03/2025",
    read: true,
    type: "verification",
  },
  {
    id: "n4",
    userId: "u3",
    title: "Monthly Deposit",
    message: "It's time to make your monthly deposit of ৳2,000 for May 2025.",
    date: "05/01/2025",
    read: true,
    type: "monthly",
  },
]

// Dummy withdrawal data
export const withdrawalData = [
  {
    id: "w1",
    purpose: "Emergency Fund",
    amount: 15000,
    details: "Medical emergency for family member",
    date: "05/05/2025",
    status: "pending",
    requestedBy: "Rahul Khan",
    userId: "m1",
    account: "main",
  },
  {
    id: "w2",
    purpose: "Equipment Purchase",
    amount: 8500,
    details: "New laptop for business operations",
    date: "04/20/2025",
    status: "approved",
    requestedBy: "Priya Sharma",
    userId: "m2",
    account: "side",
  },
  {
    id: "w3",
    purpose: "Business Investment",
    amount: 25000,
    details: "Expanding current business operations",
    date: "03/15/2025",
    status: "approved",
    requestedBy: "Amit Patel",
    userId: "m3",
    account: "main",
  },
  {
    id: "w4",
    purpose: "Medical Expenses",
    amount: 12000,
    details: "Surgery costs not covered by insurance",
    date: "02/28/2025",
    status: "rejected",
    requestedBy: "Neha Gupta",
    userId: "m4",
    account: "main",
  },
]

// Dummy member data
export const memberData = [
  {
    id: "m1",
    name: "Rahul Khan",
    email: "rahul@example.com",
    phone: "+880 1712345678",
    role: "member",
    joinDate: "01/15/2024",
    status: "active",
    totalContribution: 48000,
  },
  {
    id: "m2",
    name: "Priya Sharma",
    email: "priya@example.com",
    phone: "+880 1812345678",
    role: "member",
    joinDate: "01/20/2024",
    status: "active",
    totalContribution: 42000,
  },
  {
    id: "m3",
    name: "Amit Patel",
    email: "amit@example.com",
    phone: "+880 1912345678",
    role: "finance_manager",
    joinDate: "01/10/2024",
    status: "active",
    totalContribution: 38000,
  },
  {
    id: "m4",
    name: "Neha Gupta",
    email: "neha@example.com",
    phone: "+880 1612345678",
    role: "member",
    joinDate: "02/05/2024",
    status: "active",
    totalContribution: 35000,
  },
  {
    id: "m5",
    name: "Vikram Singh",
    email: "vikram@example.com",
    phone: "+880 1512345678",
    role: "member",
    joinDate: "02/15/2024",
    status: "active",
    totalContribution: 32000,
  },
  {
    id: "m6",
    name: "Admin User",
    email: "admin@example.com",
    phone: "+880 1312345678",
    role: "admin",
    joinDate: "01/01/2024",
    status: "active",
    totalContribution: 50000,
  },
]

// Add activity logs
export const activityLogs = [
  {
    id: "log1",
    action: "deposit",
    description: "Deposit verified for May 2025",
    amount: 2000,
    date: "05/01/2025",
    userId: "u3",
    userName: "Regular Member",
    performedBy: "u2",
    performedByName: "Finance Manager",
  },
  {
    id: "log2",
    action: "withdrawal",
    description: "Withdrawal approved for Equipment Purchase",
    amount: 8500,
    date: "04/20/2025",
    userId: "m2",
    userName: "Priya Sharma",
    performedBy: "u2",
    performedByName: "Finance Manager",
  },
  {
    id: "log3",
    action: "user_added",
    description: "New member added to the system",
    date: "04/15/2025",
    userId: "m5",
    userName: "Vikram Singh",
    performedBy: "u1",
    performedByName: "Admin User",
  },
  {
    id: "log4",
    action: "transfer",
    description: "Funds transferred from Main to Side account",
    amount: 20000,
    date: "04/10/2025",
    performedBy: "u2",
    performedByName: "Finance Manager",
  },
  {
    id: "log5",
    action: "deposit_partial",
    description: "Partial deposit for May 2025",
    amount: 1000,
    date: "05/12/2025",
    userId: "u2",
    userName: "Finance Manager",
    performedBy: "u2",
    performedByName: "Finance Manager",
  },
]
