name: Monthly Database Backup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Required Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure Rclone from Secret
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF_BASE64 }}" | base64 --decode > ~/.config/rclone/rclone.conf
        
      - name: Perform Backup and Upload
        env:
          NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
        run: |
          FILENAME="backup-$(date +'%Y-%m-%d').sql.gz"
          echo "Creating backup file: $FILENAME"
          
          pg_dump "$NEON_DATABASE_URL" | gzip > $FILENAME
          
          echo "Uploading to Google Drive..."
          # This command now uses the named remote and uploads to the folder by name
          rclone copy $FILENAME gdrive_backup:"Final Backups" -v
          
          rm $FILENAME
          echo "Backup complete."
