name: Monthly Database Backup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Required Tools
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17
          curl https://rclone.org/install.sh | sudo bash

      - name: Create Service Account Key Files from Base64 Secrets
        run: |
          echo "${{ secrets.GDRIVE_SA_KEY_1 }}" | base64 --decode > gdrive1.json
          echo "${{ secrets.GDRIVE_SA_KEY_2 }}" | base64 --decode > gdrive2.json
        
      - name: Perform Backup and Upload to Both Drives
        env:
          NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
        run: |
          FILENAME="backup-$(date +'%Y-%m-%d').sql.gz"
          echo "Creating backup file: $FILENAME"
          
          /usr/lib/postgresql/17/bin/pg_dump "$NEON_DATABASE_URL" | gzip > $FILENAME
          
          echo "Uploading to first Google Drive..."
          # THIS IS THE CORRECTED COMMAND using the Folder ID
          rclone copy $FILENAME :drive: --drive-root-folder-id ${{ secrets.GDRIVE_FOLDER_ID_1 }} --drive-service-account-file gdrive1.json -v
          
          echo "Uploading to second Google Drive..."
          # THIS IS THE CORRECTED COMMAND using the Folder ID
          rclone copy $FILENAME :drive: --drive-root-folder-id ${{ secrets.GDRIVE_FOLDER_ID_2 }} --drive-service-account-file gdrive2.json -v
          
          rm $FILENAME
          echo "Backup complete."
