name: Monthly Database Backup

on:
  # Allows manual runs from the Actions tab for testing
  workflow_dispatch:

  # Runs on the 1st day of every month at 2:00 AM UTC
  schedule:
    - cron: '0 2 1 * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Required Tools
        run: |
          # Add the official PostgreSQL repository to get the latest versions
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          
          # Install PostgreSQL client version 17 to match the Neon server
          sudo apt-get install -y postgresql-client-17
          
          # Install rclone for Google Drive uploads
          curl https://rclone.org/install.sh | sudo bash

      - name: Create Service Account Key Files from Secrets
        run: |
          echo "${{ secrets.GDRIVE_SA_KEY_1 }}" > gdrive1.json
          # echo "${{ secrets.GDRIVE_SA_KEY_2 }}" > gdrive2.json
        
      - name: Perform Backup and Upload to Both Drives
        env:
          NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
        run: |
          # Create a unique, compressed filename
          FILENAME="backup-$(date +'%Y-%m-%d').sql.gz"
          echo "Creating backup file: $FILENAME"
          
          # Use the full path to the v17 executable to ensure the correct version is used
          # Dump the database and compress it on the fly
          /usr/lib/postgresql/17/bin/pg_dump "$NEON_DATABASE_URL" | gzip > $FILENAME
          
          # Upload to the first Google Drive
          echo "Uploading to first Google Drive..."
          rclone copy $FILENAME :drive:/Neon-Backups/ --drive-service-account-file gdrive1.json -v
          
          # # Upload to the second Google Drive
          # echo "Uploading to second Google Drive..."
          # rclone copy $FILENAME :drive:/Neon-Backups-Redundant/ --drive-service-account-file gdrive2.json -v
          
          # Clean up the local file on the runner
          rm $FILENAME
          echo "Backup complete."
