name: Monthly Database Backup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      # This step correctly installs the newer postgresql-client-17
      - name: Install Required Tools
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17
          curl https://rclone.org/install.sh | sudo bash

      # This step correctly configures rclone using the direct user authentication
      - name: Configure Rclone from Secret
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF_BASE64 }}" | base64 --decode > ~/.config/rclone/rclone.conf
        
      # This step correctly creates and uploads the backup
      - name: Perform Backup and Upload
        env:
          NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
        run: |
          FILENAME="backup-$(date +'%Y-%m-%d').sql.gz"
          echo "Creating backup file: $FILENAME"
          
          # This uses the correct pg_dump command
          pg_dump "$NEON_DATABASE_URL" | gzip > $FILENAME
          
          echo "Uploading to Google Drive..."
          # This uses the correct rclone command that is now working
          rclone copy $FILENAME gdrive_backup:"Final Backups" -v
          
          rm $FILENAME
          echo "Backup complete."
